as yet unclassified
data
	^ '{
		#class : #TUAEvent,
		#obfuscated : false,
		#dataVersion : 0.13,
		#type : #testData,
		#entity : {
			''endDate'' : ''Wed 31, 2017 3:10:8 PM'',
			''userId'' : ''9c93cacd737848f48858a33179a1003a'',
			''type'' : ''testRunner'',
			''testClasses'' : OrderedCollection [
				{
					''status'' : ''PASS'',
					''name'' : ''ExpressionWatcherTest'',
					''duration'' : 0.141334,
					''testMethods'' : OrderedCollection [
						{
							''status'' : ''PASS'',
							''name'' : ''ExpressionWatcherTest>>#testWatchOverWhenExecuting'',
							''duration'' : 0.141458
						}
					]
				}
			],
			''startDate'' : ''Wed 31, 2017 3:10:8 PM''
		}
	}'